=== saisumughis/egen-be-challenge/org.egen.challenge/src/main/resources/schema.json
{  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "firstName": {
      "type": "string"
    },
    "lastName": {
      "type": "string"
    },
    "email": {
      "type": "string"
    },
    "address": {
      "type": "object",
      "properties": {
        "street": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "zip": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "country": {
          "type": "string"
        }
      },
      "required": [
        "street",
        "city",
        "zip",
        "state",
        "country"
      ]
    },
    "dateCreated": {
      "type": "string"
    },
    "company": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "website": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "website"
      ]
    },
    "profilePic": {
      "type": "string"
    }
  },
  "required": [
    "id",
    "firstName",
    "lastName",
    "email",
    "address",
    "dateCreated",
    "company",
    "profilePic"
  ]
}

=== saisumughis/egen-be-challenge/org.egen.challenge/target/classes/user2.json
{  
   "id":"2",
   "firstName":"Harris",
   "lastName":"Keeling",
   "email":"Darby_Leffler68@gmail.com",
   "address":{  
      "street":"193 Talon Valley",
      "city":"South Tate furt",
      "zip":"47069",
      "state":"IA",
      "country":"US"
   },
   "dateCreated":"2016-03-15T07:02:40.896Z",
   "company":{  
      "name":"Denesik Group",
      "website":"http://jodie.org"
   },
   "profilePic":"http://lorempixel.com/640/480/people"
}
